### ISSUE TITLE
Error on 'get status' as no user set.

### ISSUE THREAD

**Issue by erogol** [mozilla/snakepit-client#6]
I tried to run ```get status``` after I install pit and set a .pitconnect file. It asked for an user name. As I typed it in, it raised the following error.

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "/users/erogol/exists"
    at Request.init (/Users/mozilla/projects/snakepit-client/node_modules/request/request.js:273:31)
    at new Request (/Users/mozilla/projects/snakepit-client/node_modules/request/request.js:127:8)
    at request (/Users/mozilla/projects/snakepit-client/node_modules/request/index.js:53:10)
    at Function.get (/Users/mozilla/projects/snakepit-client/node_modules/request/index.js:61:12)
    at sendRequest (/Users/mozilla/projects/snakepit-client/src/pit.js:94:33)
    at callPit (/Users/mozilla/projects/snakepit-client/src/pit.js:175:13)
    at updateStatus (/Users/mozilla/projects/snakepit-client/src/pit.js:821:13)
    at Command.<anonymous> (/Users/mozilla/projects/snakepit-client/src/pit.js:870:9)
    at Command.listener (/Users/mozilla/projects/snakepit-client/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
Emitted 'error' event at:
    at Request.init (/Users/mozilla/projects/snakepit-client/node_modules/request/request.js:273:17)
    at new Request (/Users/mozilla/projects/snakepit-client/node_modules/request/request.js:127:8)
    [... lines matching original stack trace ...]
    at Command.emit (events.js:182:13)
```

**Comment by tilmankamp** [comment]
@erogol For the sake of reproducibility: What was the exact name and location of the `.pitconnect.txt` and the `.pituser.txt` files?

**Comment by erogol** [comment]
I did not copied these files. I just create a fresh .pitconnect.txt on my home folder.

**Comment by tilmankamp** [comment]
I think this got solved in the meantime. Just open another issue, if this happens again.
